### ISSUE TITLE
debian9 2017-12-19 missing two packages in stable

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/base-images-docker#157]
When running `apt-get update` on the latest image, there are two packages that are out of date:

`base-files`: Container: `9.9+deb9u2`; Latest: `9.9+deb9u3`
`sensible-utils`: Container: `0.0.9`; Latest: `0.0.9+deb9u1`

Looking at the Debian changelog, these are unimportant, but I'm a bit surprised that the `base-files` update dated "Sun, 19 Nov 2017 16:25:10 +0100" in the Changelog is missing. The `sensible-utils` one makes more sense: It is a security update from 2017-12-20.

AFAICT, the `WORKSPACE` specifies `DEB_SNAPSHOT = "20171218T034107Z"`. I grabbed `Packages.gz` from: http://snapshot.debian.org/archive/debian/20171218T034107Z/dists/stretch/main/binary-amd64/

It clearly contains a reference `base-files` version `9.9+deb9u3`, which should be what is picked up by the bazel rules ... I think. Is it possible that something went wrong when building this release?

I'm referring to the container with `sha256:6c76ed9ff726a1433243c3c2e8806e4f2ef2cbacddaca7c9e15f7d4312b1bb9f`

**Comment by sharifelgamal** [comment]
This was fixed with the release today.
