### ISSUE TITLE
Timezone no longer set in Ubuntu 18 Beta

### ISSUE THREAD

**Issue by lukasberger** [GoogleCloudPlatform/base-images-docker#201]
In ubuntu 16, the timezone was set to etc/utc by default, in ubuntu 18 a default timezone is not set, which causes a configuration dialog to show up when apt-get installing tzdata.

$ docker pull gcr.io/gcp-runtimes/ubuntu_16_0_4
$ docker run --rm -it gcr.io/gcp-runtimes/ubuntu_16_0_4 ls -l /etc/localtime
lrwxrwxrwx 1 root root 27 Jan  1  1970 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC

$ docker pull gcr.io/google-appengine-qa/ubuntu_18_0_4:beta
$ docker run --rm -it gcr.io/google-appengine-qa/ubuntu_18_0_4:beta ls -l /etc/localtime
ls: cannot access '/etc/localtime': No such file or directory

**Comment by dlorenc** [comment]
I did a bit of debugging. The symlink definitely isn't present anymore in the 18 tarball we're getting from canonical.

Interestingly enough, the symlink in the initial tarball we get is dangling - there is no file in the /usr/share/zoneinfo/Etc/UTC directory.

```shell
docker run -it gcr.io/gcp-runtimes/ubuntu_16_0_4 bash
cat /usr/share/zoneinfo/Etc/UTC
cat: /usr/share/zoneinfo/Etc/UTC: No such file or directory
```

What use-case do you have for this file? Should we just add in a dangling symlink or do you need the whole tzdata package?

**Comment by lukasberger** [comment]
We don't need tzdata to be in the base image, but it gets installed as a dependency of one of the packages that we add. I was just surprised that the same apt-get install that worked on 16 no longer works on 18. I also found that the interactive configuration can be disabled with DEBIAN_FRONTEND=noninteractive, so if the missing UTC timezone configuration is expected in ubuntu 18, then it's not an problem for us and this issue can be closed.

**Comment by sharifelgamal** [comment]
I'm adding a PR to add in DEBIAN_FRONTEND=noninteractive to all our images. Closing this.
